---
title: "Atrazine analysis"
output: Rmarkdown
author: "Muhammad"
---
```{r}
#working with data processed from qiime2:
#metadata, dada2 feature table, taxonomy assignments & rooted-tree(insertion tree)

```

#load packages
```{r}
library(tidyverse)
library(qiime2R) # A package for importing qiime artifacts. 
library(microbiome) # for data analysis and visualisation.
library(DT)
library(data.table)
library(ggpubr)
library(R2PPT)
library(RDCOMClient)
library(png)
library(vegan)
library(DESeq2)
library(viridis)

```


#convert the qiime artifacts to phyloseq objects
```{r}
#important information needed:features, tree,& #metadata.
phy_atr <- qza_to_phyloseq( 
  features = "filtered_table.qza",
  tree = "insertion-tree.qza","taxonomy.qza",
  metadata = "met-atr.tsv")

```

```{r}
phy_atr
```

#visualise the composition of the samples
```{r}
#inspect the sample reads.

summary(sample_sums(phy_atr))
```


```{r}
set.seed(9242)# This will help in reproducing the filtering and nomalisation.
p_atr <- rarefy_even_depth(phy_atr, sample.size = 4896)
```

```{r}
table(tax_table(p_atr)[, "Phylum"], exclude = NULL)
```


```{r}
#if any phylum has only one feature, consider filtering out.

p_atr <- subset_taxa(p_atr, !is.na(Phylum) & !Phylum %in% c("", "NA", "Deinococcota"))
p_atr
```


```{r}
#compute the prevalence of each OTU and store in a dataframe
prevdf_at <- apply(X = otu_table(p_atr),
               MARGIN = ifelse(taxa_are_rows(p_atr), yes = 1, no = 2),
               FUN = function(OTU){sum(OTU > 0)})
```

```{r}
#Add taxonomy and total read counts to this dataframe.

prevdf_at <- data.frame(Prevalence = prevdf_at,
                    TotalAbundance =
                  taxa_sums(p_atr),
                  tax_table(p_atr))
```


```{r}

#Define prevalence threshold as 1% of total samples
prevalenceThreshold <- 0.001 * nsamples(p_atr)
```

```{r}
#execute the prevalence filter using the prune_taxa() function.

keepTaxa <- rownames(prevdf_at)[(prevdf_at$Prevalence >= prevalenceThreshold)]
at_filt <- prune_taxa(keepTaxa, p_atr)
at_filt
```


```{r}
merge_less_than_top_at <- function(at_filt, top = 10) {transformed <- transform_sample_counts(at_filt, function(OTU) OTU/sum(OTU))
otu.table <- as.data.frame(otu_table(transformed))
otu.sort <- otu.table[order(rowMeans(otu.table), decreasing = TRUE),]
otu.list <- row.names(otu.sort[(top + 1):nrow(otu.sort),])
merged <- merge_taxa(transformed, otu.list, 1)
for(i in 1:dim(tax_table(merged))[1]){
  if (is.na(tax_table(merged)[i,2])){
    taxa_names(merged)[i] <- "Other"
    tax_table(merged)[i, 1:6] <- "Other" 
  }
}
  return(merged)
}
```


```{r}
at_gen <-tax_glom(at_filt, "Genus")
```


```{r}
at_gen_top10 <- merge_less_than_top_at(at_gen, top = 10)

```

```{r}
#convert into a dataframe.
tax_rel_abun_at_gen_top10 <-psmelt(at_gen_top10)%>%
  filter(Abundance > 0.001) %>%
  arrange(Genus)

```

```{r}
at <- ggplot(
  tax_rel_abun_at_gen_top10, aes(x = Day, y = Abundance, fill = Genus)
)+
  facet_grid(~Genotype*Treatment, scales = "free")+
  geom_bar(stat = "identity", position = "fill")+
  labs(x="Day", y="Rel. Abun", title = "Genus relative abundance") +
   theme(
    axis.text.x = element_text(size = 10, 
    angle = 90, vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size = 8),
    legend.text = element_text(size = 8),
    strip.text = element_text(size = 8)
  )
```


```{r}
at
```

```{r}
a_point <- tax_rel_abun_at_gen_top10 %>%
  mutate(Genus_ed = case_when(is.na(Genus) ~ "Other", TRUE ~ as.character(Genus))) %>% #this part changes everything that's uncharacterised to be called other
  filter(Abundance > 0.01) %>% # filter out anything less than 2% abundance
  ggplot(aes(Day,
             Genus_ed, color =
               Genus_ed)) +
  geom_point(aes(size = 
                   Abundance, 
                 fill = Genus_ed)) + #when size = Abundance, it changes the size to depend on the relative abundance in the dataframe.
facet_grid(~Genotype*Treatment) +
  labs(x="Day", y="Rel. Abun", title = "Genus relative abundance") +
   theme(
    axis.text.x = element_text(size = 10, 
    angle = 90, vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size = 8),
    legend.text = element_text(size = 8),
    strip.text = element_text(size = 8)
  )

```


```{r}
a_point
```

```{r}
# step 1:
# create a temporary file FOR the plots
TEMP_FILE <- paste(tempfile(), ".wmf", sep = "")
ggsave(TEMP_FILE, plot =atr) 
```


```{r}
 #Step 2:
#open a blank powerpoint slide.

mkppt <- PPT.Init(method = "RDCOMClient") # Run once for each R session.

```

```{r}
# Step 3:
# export the graphs to Powerpoint slides.
mkppt <- PPT.AddGraphicstoSlide(mkppt, file = TEMP_FILE)
unlink(TEMP_FILE)
```

```{r}
```


```{r}
#beta-diversity metrics: Non-phylogenetic beta diversity.

dist_at <- phyloseq::distance(
p_atr, method = "bray")
ordination <- ordinate(p_atr, method = "PCoA",
                       distance = dist_at)
b.div.bray_at <-plot_ordination(p_atr, ordination,type = "samples", shape = "Treatment", color = "Genotype", title = "PCoA; taxa(Genus)")+
  scale_color_manual(values = c("LR2_36_1" ="black", "LRV_0_1" ="red", "LRV_12_3" ="blue" , "LRV_8-5_3" ="green")) +
  geom_point(alpha = 0.7, size = 3.5) +
  coord_fixed() 
```

```{r}
print(b.div.bray_at)
```

```{r}
#Phylogenetic beta diversity metrics.

at_rel <- microbiome::transform(phy_atr, "compositional") # first transform the phyloseq object
```

```{r}
at.ord.wuni <- ordinate(at_rel, "PCoA", "unifrac", weighted = T)
```

```{r}
b.div.wuni <- plot_ordination(at_rel, at.ord.wuni, type = "samples", color = "Genotype", title = "PCoA; taxa(Genus)", shape = "Treatment")+
  geom_point( size = 3.5) +
    scale_color_manual(values = c("LR2_36_1" ="black", "LRV_0_1" ="red", "LRV_12_3" ="blue" , "LRV_8-5_3" ="green")) +
  geom_point(alpha = 0.7, size = 3.5) +
  coord_fixed() 
```

```{r}
print(b.div.wuni)
```

```{r}
#Permanova

otu <- abundances(at_rel)
meta <- meta(at_rel)

```


```{r}
permanova_at <-
adonis2(t(otu)~Treatment*Day*Genotype+(1/Genotype/Replicates), data = meta, strata = meta$Replicates, permutations = 999, method = "bray")
```

```{r}
permanova_at
```


#Differential abundance analysis
```{r}
library(ANCOMBC)

```

